defaults: &defaults
  default_user_approved: true
  version: 0.0.1
  
development:
  <<: *defaults
  
test:
  <<: *defaults
  default_user_approved: false
  
production:
  <<: *defaults
  default_user_approved: false
